# Running Heart Rate Analysis
This notebook will explore how heart rate changes during running.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
import pandas as pd

df = pd.read_csv("data/archive/s1_summaries.csv")

df.head()

,event_id,lat_median,long_median,timezone,heart_rate_median,heart_rate_50w,heart_rate_10,heart_rate_25,heart_rate_75,heart_rate_90,...,speed_proportion__16_17,speed_proportion__17_18,speed_proportion__18_19,speed_proportion__19_20,speed_proportion__20_22,speed_proportion__22_25,speed_proportion__25,total_time_spent_running,proportion_time_spent_running,proportion_rest_time
0,1,41.966027,-87.646939,America/Chicago,151.0,150.352473,137.0,144.0,153.0,155.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,1318,1.000000,0.000000
1,2,41.975176,-87.650256,America/Chicago,158.0,157.631892,144.0,152.0,161.0,162.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,1643,1.000000,0.000000
2,3,41.964429,-87.642942,America/Chicago,161.0,160.624177,133.5,151.0,166.0,169.0,...,0.031447,0.013103,0.004193,0.00131,0.000524,0.001048,0.0,3809,0.740618,0.259382
3,4,41.940418,-87.637683,America/Chicago,148.0,148.030029,143.0,146.0,156.0,159.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,4735,0.958890,0.041110
4,5,41.965287,-87.648160,America/Chicago,161.0,160.438884,148.0,155.0,165.0,166.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,1562,1.000000,0.000000

In [12]:
df.columns

Index(['event_id', 'lat_median', 'long_median', 'timezone',
       'heart_rate_median', 'heart_rate_50w', 'heart_rate_10', 'heart_rate_25',
       'heart_rate_75', 'heart_rate_90',
       ...
       'speed_proportion__16_17', 'speed_proportion__17_18',
       'speed_proportion__18_19', 'speed_proportion__19_20',
       'speed_proportion__20_22', 'speed_proportion__22_25',
       'speed_proportion__25', 'total_time_spent_running',
       'proportion_time_spent_running', 'proportion_rest_time'],
      dtype='object', length=145)

In [8]:
import pandas as pd

df2 = pd.read_csv("data/Strava Running Data.csv")
df2.head()

,Sr. no.,start_date_local,type,distance,moving_time,elapsed_time,total_elevation_gain,start_latlng,end_latlng,sport_type,start_date,timezone,achievement_count,kudos_count,comment_count,athlete_count,photo_count,average_speed,max_speed
0,1,2023-12-09T09:09:19Z,Run,10879.7,4023,4617,91.4,"[40.70327935740352, -73.99619171395898]","[40.69340907968581, -73.97922154515982]",Run,2023-12-09T14:09:19Z,(GMT-05:00) America/New_York,4,4,0,3,0,2.704,6.228
1,2,2023-12-07T17:31:50Z,Run,1304.4,722,62993,0.0,"[40.7220459356904, -74.03641730546951]","[40.719722136855125, -74.03257705271244]",Run,2023-12-07T22:31:50Z,(GMT-05:00) America/New_York,0,0,0,1,0,1.807,4.044
2,3,2023-12-03T09:18:13Z,Run,17503.0,7370,7462,68.4,"[40.74991073459387, -73.98751585744321]","[40.73538766242564, -73.9793517999351]",Run,2023-12-03T14:18:13Z,(GMT-05:00) America/New_York,2,5,0,4,0,2.375,6.778
3,4,2023-12-02T09:41:14Z,Run,3457.8,1791,2170,3.9,"[40.72203076444566, -74.03641068376601]","[40.71398631669581, -74.03902692720294]",Run,2023-12-02T14:41:14Z,(GMT-05:00) America/New_York,0,2,0,3,0,1.931,4.522
4,5,2023-12-01T17:06:05Z,Run,10108.2,4128,4221,6.3,"[40.72190687991679, -74.03624514117837]","[40.71669920347631, -74.03264125809073]",Run,2023-12-01T22:06:05Z,(GMT-05:00) America/New_York,4,5,0,1,0,2.449,5.462

In [9]:
df2.columns

Index(['Sr. no.', 'start_date_local', 'type', 'distance', 'moving_time',
       'elapsed_time', 'total_elevation_gain', 'start_latlng', 'end_latlng',
       'sport_type', 'start_date', 'timezone', 'achievement_count',
       'kudos_count', 'comment_count', 'athlete_count', 'photo_count',
       'average_speed', 'max_speed'],
      dtype='object')

In [13]:
df3 = pd.read_csv("data/activity_log.csv")
df3.head()

,Activity Type,Date,Title,Distance,Calories,Time,Avg HR,Max HR,Avg Run Cadence,Max Run Cadence,Avg Pace,Best Pace,Elev Gain,Elev Loss,Avg Stride Length,Best Lap Time,Number of Laps
0,Running,7/15/20 9:41,Cherry Hill Running,6.00,530,0:43:55,141,160,176,182,7:19,6:20,169,173,1.26,00:02.3,7
1,Running,7/14/20 17:45,Cherry Hill Running,6.50,587,0:47:04,144,160,172,182,7:14,6:35,183,187,1.29,03:32.7,7
2,Running,7/13/20 18:57,Cherry Hill Running,5.01,392,0:40:29,128,151,170,180,8:05,5:49,124,124,1.17,00:04.1,6
3,Running,7/12/20 18:44,Cherry Hill Running,7.01,633,0:52:55,142,157,172,180,7:33,5:00,215,219,1.24,00:05.1,8
4,Running,7/11/20 19:35,Cherry Hill Running,5.19,419,0:41:35,129,143,170,178,8:01,6:48,76,80,1.18,01:27.1,6

In [14]:
df3.columns

Index(['Activity Type', 'Date', 'Title', 'Distance', 'Calories', 'Time',
       'Avg HR', 'Max HR', 'Avg Run Cadence', 'Max Run Cadence', 'Avg Pace',
       'Best Pace', 'Elev Gain', 'Elev Loss', 'Avg Stride Length',
       'Best Lap Time', 'Number of Laps'],
      dtype='object')